use async_trait::async_trait;

use super::{Command, CommandResult, SessionInfo};

pub struct HelpCommand;

#[async_trait]
impl Command for HelpCommand {
    fn name(&self) -> &str {
        "/help"
    }

    fn aliases(&self) -> &[&str] {
        &["/h", "/?"]
    }

    fn description(&self) -> &str {
        "show this help"
    }

    /// Help output is generated by the registry, not here.
    /// The registry intercepts `/help` in `dispatch()` so it can
    /// list all registered commands including plugins.
    async fn execute(&self, _info: &SessionInfo<'_>) -> CommandResult {
        CommandResult::Handled
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn has_aliases() {
        let aliases = HelpCommand.aliases();
        assert!(aliases.contains(&"/h"));
        assert!(aliases.contains(&"/?"));
    }
}
